### ISSUE TITLE
Don't preview "tel:" links

### ISSUE THREAD

**Issue by tberneman** [soderlind/wp-live-preview-links#1]
I have your plugin setup to display external links only. When it runs across a "tel:" link the preview pops up with the spinner and nothing happens. Your plugin should ignore telephone links.

**Comment by tberneman** [comment]
An alternative (maybe an option) would be to show the popup with "Click this link to dial the number if your device supports it." or something similar.

**Comment by soderlind** [comment]
Use the jquery selector in https://github.com/soderlind/wp-live-preview-links/issues/4
