### ISSUE TITLE
Google maps don't preview

### ISSUE THREAD

**Issue by tberneman** [soderlind/wp-live-preview-links#3]
I have your plugin setup to display external links only. When I hover over a google maps link the spinner spins but nothing ever happens.

**Comment by soderlind** [comment]
Please see the FAQ: https://github.com/soderlind/wp-live-preview-links#it-doesnt-work-

**Comment by tberneman** [comment]
This is an example where a class to not show the preview would come in handy! :)

**Comment by soderlind** [comment]
See https://github.com/soderlind/wp-live-preview-links/issues/4
